export const data = [
  {
    id: 1,
    name: "John ",
    lastMessage: "Hello",
    time: new Date().toLocaleTimeString(),
    unread: 5,
  },
  {
    id: 2,
    name: "Rohan Das",
    lastMessage: "Done ",
    time: new Date().toLocaleTimeString(),
    unread: 2,
  },
  {
    id: 3,
    name: "Vishal Singh",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 1,
  },
  {
    id: 4,
    name: "Rahul Singh",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 0,
  },
  {
    id: 5,
    name: "Neha",
    lastMessage: "Let See",
    time: new Date().toLocaleTimeString(),
    unread: 4,
  },
  {
    id: 6,
    name: "Salman",
    lastMessage: "Hello",
    time: new Date().toLocaleTimeString(),
    unread: 6,
  },
  {
    id: 7,
    name: "Shilpa",
    lastMessage: "Done ",
    time: new Date().toLocaleTimeString(),
    unread: 2,
  },
  {
    id: 8,
    name: "Tanisha Office",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 1,
  },
  {
    id: 9,
    name: "Mehul Sir",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 0,
  },
  {
    id: 10,
    name: "Virat",
    lastMessage: "Let See",
    time: new Date().toLocaleTimeString(),
    unread: 4,
  },
  {
    id: 11,
    name: "John ",
    lastMessage: "Hello",
    time: new Date().toLocaleTimeString(),
    unread: 0,
  },
  {
    id: 12,
    name: "Rohan Das",
    lastMessage: "Done ",
    time: new Date().toLocaleTimeString(),
    unread: 5,
  },
  {
    id: 13,
    name: "Vishal Singh",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 11,
  },
  {
    id: 14,
    name: "Rahul Singh",
    lastMessage: "Ok! Tommorrow  ",
    time: new Date().toLocaleTimeString(),
    unread: 4,
  },
  {
    id: 15,
    name: "Neha",
    lastMessage: "I am Fine",
    time: new Date().toLocaleTimeString(),
    unread: 3,
  },
  {
    id: 16,
    name: "Salman",
    lastMessage: "NExt Time",
    time: new Date().toLocaleTimeString(),
    unread: 0,
  },
  {
    id: 17,
    name: "Shilpa",
    lastMessage: "Done ",
    time: new Date().toLocaleTimeString(),
    unread: 6,
  },
  {
    id: 18,
    name: "Tanisha Office",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 1,
  },
  {
    id: 19,
    name: "Mehul Sir",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 0,
  },
  {
    id: 20,
    name: "Virat",
    lastMessage: "Let See",
    time: new Date().toLocaleTimeString(),
    unread: 4,
  },
  {
    id: 21,
    name: "John ",
    lastMessage: "Hello",
    time: new Date().toLocaleTimeString(),
    unread: 5,
  },
  {
    id: 22,
    name: "Rohan Das",
    lastMessage: "Done ",
    time: new Date().toLocaleTimeString(),
    unread: 2,
  },
  {
    id: 23,
    name: "Vishal Singh",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 1,
  },
  {
    id: 24,
    name: "Rahul Singh",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 0,
  },
  {
    id: 25,
    name: "Neha",
    lastMessage: "Let See",
    time: new Date().toLocaleTimeString(),
    unread: 4,
  },
  {
    id: 26,
    name: "Salman",
    lastMessage: "Hello",
    time: new Date().toLocaleTimeString(),
    unread: 6,
  },
  {
    id: 27,
    name: "Shilpa",
    lastMessage: "After 2 days",
    time: new Date().toLocaleTimeString(),
    unread: 7,
  },
  {
    id: 28,
    name: "Tanisha Office",
    lastMessage: "Yes, I am available",
    time: new Date().toLocaleTimeString(),
    unread: 4,
  },
  {
    id: 29,
    name: "Mehul Sir",
    lastMessage: "Ok",
    time: new Date().toLocaleTimeString(),
    unread: 5,
  },
  {
    id: 30,
    name: "Virat",
    lastMessage: "Ha Thik hai",
    time: new Date().toLocaleTimeString(),
    unread: 45,
  },
];
