export const data = [
  {
    id: 1,
    name: "John ",
    lastMessage: "Hello",
    time: new Date().toLocaleTimeString(),
    unread: 5,
  },
  {
    id: 2,
    name: "Rohan Das",
    lastMessage: "Done ",
    time: new Date().toLocaleTimeString(),
    unread: 2,
  },
  {
    id: 3,
    name: "Vishal Singh",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 1,
  },
  {
    id: 4,
    name: "Rahul Singh",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 0,
  },
  {
    id: 5,
    name: "Neha",
    lastMessage: "Let See",
    time: new Date().toLocaleTimeString(),
    unread: 4,
  },
  {
    id: 6,
    name: "Salman",
    lastMessage: "Hello",
    time: new Date().toLocaleTimeString(),
    unread: 6,
  },
  {
    id: 7,
    name: "Shilpa",
    lastMessage: "Done ",
    time: new Date().toLocaleTimeString(),
    unread: 2,
  },
  {
    id: 8,
    name: "Tanisha Office",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 1,
  },
  {
    id: 9,
    name: "Mehul Sir",
    lastMessage: "Ok ",
    time: new Date().toLocaleTimeString(),
    unread: 0,
  },
  {
    id: 10,
    name: "Virat",
    lastMessage: "Let See",
    time: new Date().toLocaleTimeString(),
    unread: 4,
  },
];
